### ISSUE TITLE
Not clear expired content on CacheManager init

### ISSUE THREAD

**Issue by jlsandrin** [hyperoslo/Cache#116] opened 2017-08-22 17:39 UTC
I'm using Cache to store JSON coming from the server. This content is updated everyday, so I'm setting it's expiration date to be the day it was downloaded at 11:59 PM. this works just fine and the content is expired and re downloaded the next day.

The problem I'm facing is that, due to business rules, I need to return expired content (so I can have something to show user), identify that this content has expired and download the new version. And then update view with this new content and cache it.

Is there any way to flag Cache to not clear expired data on initialization, and when receiving some notifications?

**Comment by zenangst** [comment] 2017-08-24 11:51
@jlsandrin hey man, right now we don't have a way of opting out from clearing the expired objects when `CacheManager` gets initialized. This is by design so that we don't keep outdated content around. With that said, couldn't you just set the expiration date to be `nil` when storing the objects? That way they won't be cleared when `CacheManager` initializes?

**Comment by zenangst** [comment] 2017-08-28 08:48
This feels pseudo related to https://github.com/hyperoslo/Cache/issues/117.

**Comment by zenangst** [comment] 2017-08-28 09:30
@vadymmarkov could this be solved by adding a small configuration enum.

```swift
enum CacheCleanup {
  case auto, manual
}
```

`.auto` would be the default to not break the current implementation. And when you set it to `.manual`, it would simply opt out from doing any for of cleanup during application launch. This would mean that the developer would have to handle that manually (which I think is okay).

**Comment by vadymmarkov** [comment] 2017-08-28 10:07
@zenangst Yes, that should work I think.

**Comment by jlsandrin** [comment] 2017-08-28 13:39
I agree with clearing objects on init. I personally prefer an option like that, but unfortunately this app can't work this way. 

The problem with setting the expiration to nil is that I can't handle if content is "old" or not (or at least I couldn't find a way). I download something new whenever expiration date is older than current date, while not deleting what is in store.

`.manual` option would be perfect for what I need.

**Comment by zenangst** [comment] 2017-08-28 16:53
@jlsandrin ohai, I whipped up a small PR to implement this feature, you can find it here https://github.com/hyperoslo/Cache/pull/118

**Comment by jlsandrin** [comment] 2017-08-29 17:01
Awesome, you guys rock!

**Comment by zenangst** [comment] 2017-08-29 17:50
@jlsandrin let us know how it works out! It should be on `master` now. Closing the issue.

**Closed by zenangst** 2017-08-29 17:50 UTC
Labels: enhancement
